<?php

if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class Kelola_user_model extends CI_Model
{
    public $table = 'user';
    public $id = 'id';
    public $order = 'DESC';

    public function __construct()
    {
        parent::__construct();
    }

    // datatables
    public function json()
    {
        $this->datatables->select('id,name,email,role_id,is_active');
        $this->datatables->from('user');
        //add this line for join
        //$this->datatables->join('table2', 'user.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('kelola_user/read/$1'), 'Read')." | ".anchor(site_url('kelola_user/update/$1'), 'Update')." | ".anchor(site_url('kelola_user/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Kamu yakin ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    public function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    public function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    public function total_rows($q = null)
    {
        $this->db->like('id', $q);
        $this->db->or_like('name', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('image', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('role_id', $q);
        $this->db->or_like('is_active', $q);
        $this->db->or_like('date_created', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    public function get_limit_data($limit, $start = 0, $q = null)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('name', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('image', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('role_id', $q);
        $this->db->or_like('is_active', $q);
        $this->db->or_like('date_created', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    public function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    public function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    public function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Kelola_user_model.php */
/* Location: ./application/models/Kelola_user_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-22 03:55:02 */
/* http://harviacode.com */